spring:
  application:
    name: mini-drive

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_drive_db
    username: postgres
    password: 953012


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080